version: '3.8'

services:
  villa-admin:
    container_name: ${CONTAINER_NAME:-villa-admin}
    build:
      context: .
      dockerfile: Dockerfile
    image: villa-admin:${APP_VERSION:-latest}
    restart: unless-stopped
    expose:
      - "${INTERNAL_PORT:-8000}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - ${TRAEFIK_NETWORK:-traefik-public}
    labels:
      # Habilitar Traefik
      - "traefik.enable=true"
      
      # Configuração HTTP (redireciona para HTTPS)
      - "traefik.http.routers.villa-admin-http.rule=Host(`${DOMAIN:-admin.villamarket.app}`)"
      - "traefik.http.routers.villa-admin-http.entrypoints=web"
      - "traefik.http.routers.villa-admin-http.middlewares=redirect-to-https"
      
      # Configuração HTTPS
      - "traefik.http.routers.villa-admin.rule=Host(`${DOMAIN:-admin.villamarket.app}`)"
      - "traefik.http.routers.villa-admin.entrypoints=websecure"
      - "traefik.http.routers.villa-admin.tls=true"
      - "traefik.http.routers.villa-admin.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
      
      # Configuração do serviço
      - "traefik.http.services.villa-admin.loadbalancer.server.port=${INTERNAL_PORT:-8000}"
      
      # Middleware de redirecionamento HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      
      # Metadados
      - "com.villa.description=Villa Market Admin Panel"
      - "com.villa.version=${APP_VERSION:-2.1.0}"
    
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${INTERNAL_PORT:-8000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  traefik-public:
    external: true
