/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedVendorRouteRouteImport } from './routes/_authenticated/vendor/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedStoriesIndexRouteImport } from './routes/_authenticated/stories/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPayableAccountsIndexRouteImport } from './routes/_authenticated/payable-accounts/index'
import { Route as AuthenticatedLoansIndexRouteImport } from './routes/_authenticated/loans/index'
import { Route as AuthenticatedItemsIndexRouteImport } from './routes/_authenticated/items/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedFeesIndexRouteImport } from './routes/_authenticated/fees/index'
import { Route as AuthenticatedEmprestimosIndexRouteImport } from './routes/_authenticated/emprestimos/index'
import { Route as AuthenticatedClassifiedsIndexRouteImport } from './routes/_authenticated/classifieds/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCashbackIndexRouteImport } from './routes/_authenticated/cashback/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as AuthenticatedStoriesNewRouteImport } from './routes/_authenticated/stories/new'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedLoansLoanIdRouteImport } from './routes/_authenticated/loans/$loanId'
import { Route as AuthenticatedItemsNewRouteImport } from './routes/_authenticated/items/new'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCashbackOrderIdRouteImport } from './routes/_authenticated/cashback/$orderId'
import { Route as AuthenticatedCashbackCashbackIdRouteImport } from './routes/_authenticated/cashback/$cashbackId'
import { Route as AuthenticatedVendorOrdersIndexRouteImport } from './routes/_authenticated/vendor/orders/index'
import { Route as AuthenticatedStoriesStoryIdIndexRouteImport } from './routes/_authenticated/stories/$storyId/index'
import { Route as AuthenticatedItemsItemIdIndexRouteImport } from './routes/_authenticated/items/$itemId/index'
import { Route as AuthenticatedAdminZonesIndexRouteImport } from './routes/_authenticated/admin/zones/index'
import { Route as AuthenticatedAdminStoresIndexRouteImport } from './routes/_authenticated/admin/stores/index'
import { Route as AuthenticatedAdminOrdersIndexRouteImport } from './routes/_authenticated/admin/orders/index'
import { Route as AuthenticatedAdminModulesIndexRouteImport } from './routes/_authenticated/admin/modules/index'
import { Route as AuthenticatedAdminCustomersIndexRouteImport } from './routes/_authenticated/admin/customers/index'
import { Route as AuthenticatedAdminCategoriesIndexRouteImport } from './routes/_authenticated/admin/categories/index'
import { Route as AuthenticatedAdminAccessManagementIndexRouteImport } from './routes/_authenticated/admin/access-management/index'
import { Route as AuthenticatedStoriesStoryIdEditRouteImport } from './routes/_authenticated/stories/$storyId/edit'
import { Route as AuthenticatedItemsItemIdEditRouteImport } from './routes/_authenticated/items/$itemId/edit'
import { Route as AuthenticatedAdminZonesNewRouteImport } from './routes/_authenticated/admin/zones/new'
import { Route as AuthenticatedAdminStoresNewRouteImport } from './routes/_authenticated/admin/stores/new'
import { Route as AuthenticatedAdminModulesNewRouteImport } from './routes/_authenticated/admin/modules/new'
import { Route as AuthenticatedAdminCustomersUserIdRouteImport } from './routes/_authenticated/admin/customers/$userId'
import { Route as AuthenticatedAdminCategoriesNewRouteImport } from './routes/_authenticated/admin/categories/new'
import { Route as AuthenticatedAdminStoresStoreIdIndexRouteImport } from './routes/_authenticated/admin/stores/$storeId/index'
import { Route as AuthenticatedAdminOrdersOrderIdIndexRouteImport } from './routes/_authenticated/admin/orders/$orderId/index'
import { Route as AuthenticatedAdminZonesZoneIdModulesRouteImport } from './routes/_authenticated/admin/zones/$zoneId/modules'
import { Route as AuthenticatedAdminZonesZoneIdEditRouteImport } from './routes/_authenticated/admin/zones/$zoneId/edit'
import { Route as AuthenticatedAdminStoresStoreIdEditRouteImport } from './routes/_authenticated/admin/stores/$storeId/edit'
import { Route as AuthenticatedAdminModulesModuleIdEditRouteImport } from './routes/_authenticated/admin/modules/$moduleId/edit'
import { Route as AuthenticatedAdminCategoriesCategoryIdEditRouteImport } from './routes/_authenticated/admin/categories/$categoryId/edit'
import { Route as AuthenticatedAdminAccessManagementUserIdEditRouteImport } from './routes/_authenticated/admin/access-management/$userId/edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorRouteRoute =
  AuthenticatedVendorRouteRouteImport.update({
    id: '/vendor',
    path: '/vendor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoriesIndexRoute =
  AuthenticatedStoriesIndexRouteImport.update({
    id: '/stories/',
    path: '/stories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPayableAccountsIndexRoute =
  AuthenticatedPayableAccountsIndexRouteImport.update({
    id: '/payable-accounts/',
    path: '/payable-accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoansIndexRoute = AuthenticatedLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItemsIndexRoute = AuthenticatedItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeesIndexRoute = AuthenticatedFeesIndexRouteImport.update({
  id: '/fees/',
  path: '/fees/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmprestimosIndexRoute =
  AuthenticatedEmprestimosIndexRouteImport.update({
    id: '/emprestimos/',
    path: '/emprestimos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassifiedsIndexRoute =
  AuthenticatedClassifiedsIndexRouteImport.update({
    id: '/classifieds/',
    path: '/classifieds/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashbackIndexRoute =
  AuthenticatedCashbackIndexRouteImport.update({
    id: '/cashback/',
    path: '/cashback/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoriesNewRoute = AuthenticatedStoriesNewRouteImport.update({
  id: '/stories/new',
  path: '/stories/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedLoansLoanIdRoute =
  AuthenticatedLoansLoanIdRouteImport.update({
    id: '/loans/$loanId',
    path: '/loans/$loanId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItemsNewRoute = AuthenticatedItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashbackOrderIdRoute =
  AuthenticatedCashbackOrderIdRouteImport.update({
    id: '/cashback/$orderId',
    path: '/cashback/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashbackCashbackIdRoute =
  AuthenticatedCashbackCashbackIdRouteImport.update({
    id: '/cashback/$cashbackId',
    path: '/cashback/$cashbackId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorOrdersIndexRoute =
  AuthenticatedVendorOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)
const AuthenticatedStoriesStoryIdIndexRoute =
  AuthenticatedStoriesStoryIdIndexRouteImport.update({
    id: '/stories/$storyId/',
    path: '/stories/$storyId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItemsItemIdIndexRoute =
  AuthenticatedItemsItemIdIndexRouteImport.update({
    id: '/items/$itemId/',
    path: '/items/$itemId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminZonesIndexRoute =
  AuthenticatedAdminZonesIndexRouteImport.update({
    id: '/zones/',
    path: '/zones/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStoresIndexRoute =
  AuthenticatedAdminStoresIndexRouteImport.update({
    id: '/stores/',
    path: '/stores/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersIndexRoute =
  AuthenticatedAdminOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModulesIndexRoute =
  AuthenticatedAdminModulesIndexRouteImport.update({
    id: '/modules/',
    path: '/modules/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersIndexRoute =
  AuthenticatedAdminCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesIndexRoute =
  AuthenticatedAdminCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccessManagementIndexRoute =
  AuthenticatedAdminAccessManagementIndexRouteImport.update({
    id: '/access-management/',
    path: '/access-management/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedStoriesStoryIdEditRoute =
  AuthenticatedStoriesStoryIdEditRouteImport.update({
    id: '/stories/$storyId/edit',
    path: '/stories/$storyId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItemsItemIdEditRoute =
  AuthenticatedItemsItemIdEditRouteImport.update({
    id: '/items/$itemId/edit',
    path: '/items/$itemId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminZonesNewRoute =
  AuthenticatedAdminZonesNewRouteImport.update({
    id: '/zones/new',
    path: '/zones/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStoresNewRoute =
  AuthenticatedAdminStoresNewRouteImport.update({
    id: '/stores/new',
    path: '/stores/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModulesNewRoute =
  AuthenticatedAdminModulesNewRouteImport.update({
    id: '/modules/new',
    path: '/modules/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersUserIdRoute =
  AuthenticatedAdminCustomersUserIdRouteImport.update({
    id: '/customers/$userId',
    path: '/customers/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesNewRoute =
  AuthenticatedAdminCategoriesNewRouteImport.update({
    id: '/categories/new',
    path: '/categories/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStoresStoreIdIndexRoute =
  AuthenticatedAdminStoresStoreIdIndexRouteImport.update({
    id: '/stores/$storeId/',
    path: '/stores/$storeId/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersOrderIdIndexRoute =
  AuthenticatedAdminOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminZonesZoneIdModulesRoute =
  AuthenticatedAdminZonesZoneIdModulesRouteImport.update({
    id: '/zones/$zoneId/modules',
    path: '/zones/$zoneId/modules',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminZonesZoneIdEditRoute =
  AuthenticatedAdminZonesZoneIdEditRouteImport.update({
    id: '/zones/$zoneId/edit',
    path: '/zones/$zoneId/edit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStoresStoreIdEditRoute =
  AuthenticatedAdminStoresStoreIdEditRouteImport.update({
    id: '/stores/$storeId/edit',
    path: '/stores/$storeId/edit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModulesModuleIdEditRoute =
  AuthenticatedAdminModulesModuleIdEditRouteImport.update({
    id: '/modules/$moduleId/edit',
    path: '/modules/$moduleId/edit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesCategoryIdEditRoute =
  AuthenticatedAdminCategoriesCategoryIdEditRouteImport.update({
    id: '/categories/$categoryId/edit',
    path: '/categories/$categoryId/edit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccessManagementUserIdEditRoute =
  AuthenticatedAdminAccessManagementUserIdEditRouteImport.update({
    id: '/access-management/$userId/edit',
    path: '/access-management/$userId/edit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/vendor': typeof AuthenticatedVendorRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/cashback/$cashbackId': typeof AuthenticatedCashbackCashbackIdRoute
  '/cashback/$orderId': typeof AuthenticatedCashbackOrderIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/stories/new': typeof AuthenticatedStoriesNewRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/cashback': typeof AuthenticatedCashbackIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/classifieds': typeof AuthenticatedClassifiedsIndexRoute
  '/emprestimos': typeof AuthenticatedEmprestimosIndexRoute
  '/fees': typeof AuthenticatedFeesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/loans': typeof AuthenticatedLoansIndexRoute
  '/payable-accounts': typeof AuthenticatedPayableAccountsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/stories': typeof AuthenticatedStoriesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/admin/categories/new': typeof AuthenticatedAdminCategoriesNewRoute
  '/admin/customers/$userId': typeof AuthenticatedAdminCustomersUserIdRoute
  '/admin/modules/new': typeof AuthenticatedAdminModulesNewRoute
  '/admin/stores/new': typeof AuthenticatedAdminStoresNewRoute
  '/admin/zones/new': typeof AuthenticatedAdminZonesNewRoute
  '/items/$itemId/edit': typeof AuthenticatedItemsItemIdEditRoute
  '/stories/$storyId/edit': typeof AuthenticatedStoriesStoryIdEditRoute
  '/admin/access-management': typeof AuthenticatedAdminAccessManagementIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersIndexRoute
  '/admin/modules': typeof AuthenticatedAdminModulesIndexRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/stores': typeof AuthenticatedAdminStoresIndexRoute
  '/admin/zones': typeof AuthenticatedAdminZonesIndexRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdIndexRoute
  '/stories/$storyId': typeof AuthenticatedStoriesStoryIdIndexRoute
  '/vendor/orders': typeof AuthenticatedVendorOrdersIndexRoute
  '/admin/access-management/$userId/edit': typeof AuthenticatedAdminAccessManagementUserIdEditRoute
  '/admin/categories/$categoryId/edit': typeof AuthenticatedAdminCategoriesCategoryIdEditRoute
  '/admin/modules/$moduleId/edit': typeof AuthenticatedAdminModulesModuleIdEditRoute
  '/admin/stores/$storeId/edit': typeof AuthenticatedAdminStoresStoreIdEditRoute
  '/admin/zones/$zoneId/edit': typeof AuthenticatedAdminZonesZoneIdEditRoute
  '/admin/zones/$zoneId/modules': typeof AuthenticatedAdminZonesZoneIdModulesRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdIndexRoute
  '/admin/stores/$storeId': typeof AuthenticatedAdminStoresStoreIdIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/vendor': typeof AuthenticatedVendorRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/cashback/$cashbackId': typeof AuthenticatedCashbackCashbackIdRoute
  '/cashback/$orderId': typeof AuthenticatedCashbackOrderIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/stories/new': typeof AuthenticatedStoriesNewRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/cashback': typeof AuthenticatedCashbackIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/classifieds': typeof AuthenticatedClassifiedsIndexRoute
  '/emprestimos': typeof AuthenticatedEmprestimosIndexRoute
  '/fees': typeof AuthenticatedFeesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/loans': typeof AuthenticatedLoansIndexRoute
  '/payable-accounts': typeof AuthenticatedPayableAccountsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/stories': typeof AuthenticatedStoriesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/admin/categories/new': typeof AuthenticatedAdminCategoriesNewRoute
  '/admin/customers/$userId': typeof AuthenticatedAdminCustomersUserIdRoute
  '/admin/modules/new': typeof AuthenticatedAdminModulesNewRoute
  '/admin/stores/new': typeof AuthenticatedAdminStoresNewRoute
  '/admin/zones/new': typeof AuthenticatedAdminZonesNewRoute
  '/items/$itemId/edit': typeof AuthenticatedItemsItemIdEditRoute
  '/stories/$storyId/edit': typeof AuthenticatedStoriesStoryIdEditRoute
  '/admin/access-management': typeof AuthenticatedAdminAccessManagementIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersIndexRoute
  '/admin/modules': typeof AuthenticatedAdminModulesIndexRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/stores': typeof AuthenticatedAdminStoresIndexRoute
  '/admin/zones': typeof AuthenticatedAdminZonesIndexRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdIndexRoute
  '/stories/$storyId': typeof AuthenticatedStoriesStoryIdIndexRoute
  '/vendor/orders': typeof AuthenticatedVendorOrdersIndexRoute
  '/admin/access-management/$userId/edit': typeof AuthenticatedAdminAccessManagementUserIdEditRoute
  '/admin/categories/$categoryId/edit': typeof AuthenticatedAdminCategoriesCategoryIdEditRoute
  '/admin/modules/$moduleId/edit': typeof AuthenticatedAdminModulesModuleIdEditRoute
  '/admin/stores/$storeId/edit': typeof AuthenticatedAdminStoresStoreIdEditRoute
  '/admin/zones/$zoneId/edit': typeof AuthenticatedAdminZonesZoneIdEditRoute
  '/admin/zones/$zoneId/modules': typeof AuthenticatedAdminZonesZoneIdModulesRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdIndexRoute
  '/admin/stores/$storeId': typeof AuthenticatedAdminStoresStoreIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/vendor': typeof AuthenticatedVendorRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cashback/$cashbackId': typeof AuthenticatedCashbackCashbackIdRoute
  '/_authenticated/cashback/$orderId': typeof AuthenticatedCashbackOrderIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/items/new': typeof AuthenticatedItemsNewRoute
  '/_authenticated/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/stories/new': typeof AuthenticatedStoriesNewRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/cashback/': typeof AuthenticatedCashbackIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/classifieds/': typeof AuthenticatedClassifiedsIndexRoute
  '/_authenticated/emprestimos/': typeof AuthenticatedEmprestimosIndexRoute
  '/_authenticated/fees/': typeof AuthenticatedFeesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/items/': typeof AuthenticatedItemsIndexRoute
  '/_authenticated/loans/': typeof AuthenticatedLoansIndexRoute
  '/_authenticated/payable-accounts/': typeof AuthenticatedPayableAccountsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/stories/': typeof AuthenticatedStoriesIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/admin/categories/new': typeof AuthenticatedAdminCategoriesNewRoute
  '/_authenticated/admin/customers/$userId': typeof AuthenticatedAdminCustomersUserIdRoute
  '/_authenticated/admin/modules/new': typeof AuthenticatedAdminModulesNewRoute
  '/_authenticated/admin/stores/new': typeof AuthenticatedAdminStoresNewRoute
  '/_authenticated/admin/zones/new': typeof AuthenticatedAdminZonesNewRoute
  '/_authenticated/items/$itemId/edit': typeof AuthenticatedItemsItemIdEditRoute
  '/_authenticated/stories/$storyId/edit': typeof AuthenticatedStoriesStoryIdEditRoute
  '/_authenticated/admin/access-management/': typeof AuthenticatedAdminAccessManagementIndexRoute
  '/_authenticated/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/_authenticated/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/_authenticated/admin/modules/': typeof AuthenticatedAdminModulesIndexRoute
  '/_authenticated/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/_authenticated/admin/stores/': typeof AuthenticatedAdminStoresIndexRoute
  '/_authenticated/admin/zones/': typeof AuthenticatedAdminZonesIndexRoute
  '/_authenticated/items/$itemId/': typeof AuthenticatedItemsItemIdIndexRoute
  '/_authenticated/stories/$storyId/': typeof AuthenticatedStoriesStoryIdIndexRoute
  '/_authenticated/vendor/orders/': typeof AuthenticatedVendorOrdersIndexRoute
  '/_authenticated/admin/access-management/$userId/edit': typeof AuthenticatedAdminAccessManagementUserIdEditRoute
  '/_authenticated/admin/categories/$categoryId/edit': typeof AuthenticatedAdminCategoriesCategoryIdEditRoute
  '/_authenticated/admin/modules/$moduleId/edit': typeof AuthenticatedAdminModulesModuleIdEditRoute
  '/_authenticated/admin/stores/$storeId/edit': typeof AuthenticatedAdminStoresStoreIdEditRoute
  '/_authenticated/admin/zones/$zoneId/edit': typeof AuthenticatedAdminZonesZoneIdEditRoute
  '/_authenticated/admin/zones/$zoneId/modules': typeof AuthenticatedAdminZonesZoneIdModulesRoute
  '/_authenticated/admin/orders/$orderId/': typeof AuthenticatedAdminOrdersOrderIdIndexRoute
  '/_authenticated/admin/stores/$storeId/': typeof AuthenticatedAdminStoresStoreIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/settings'
    | '/vendor'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/cashback/$cashbackId'
    | '/cashback/$orderId'
    | '/errors/$error'
    | '/items/new'
    | '/loans/$loanId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/stories/new'
    | '/users/$userId'
    | '/apps'
    | '/cashback'
    | '/chats'
    | '/classifieds'
    | '/emprestimos'
    | '/fees'
    | '/help-center'
    | '/items'
    | '/loans'
    | '/payable-accounts'
    | '/settings/'
    | '/stories'
    | '/tasks'
    | '/users'
    | '/admin/categories/new'
    | '/admin/customers/$userId'
    | '/admin/modules/new'
    | '/admin/stores/new'
    | '/admin/zones/new'
    | '/items/$itemId/edit'
    | '/stories/$storyId/edit'
    | '/admin/access-management'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/modules'
    | '/admin/orders'
    | '/admin/stores'
    | '/admin/zones'
    | '/items/$itemId'
    | '/stories/$storyId'
    | '/vendor/orders'
    | '/admin/access-management/$userId/edit'
    | '/admin/categories/$categoryId/edit'
    | '/admin/modules/$moduleId/edit'
    | '/admin/stores/$storeId/edit'
    | '/admin/zones/$zoneId/edit'
    | '/admin/zones/$zoneId/modules'
    | '/admin/orders/$orderId'
    | '/admin/stores/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/vendor'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/cashback/$cashbackId'
    | '/cashback/$orderId'
    | '/errors/$error'
    | '/items/new'
    | '/loans/$loanId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/stories/new'
    | '/users/$userId'
    | '/apps'
    | '/cashback'
    | '/chats'
    | '/classifieds'
    | '/emprestimos'
    | '/fees'
    | '/help-center'
    | '/items'
    | '/loans'
    | '/payable-accounts'
    | '/settings'
    | '/stories'
    | '/tasks'
    | '/users'
    | '/admin/categories/new'
    | '/admin/customers/$userId'
    | '/admin/modules/new'
    | '/admin/stores/new'
    | '/admin/zones/new'
    | '/items/$itemId/edit'
    | '/stories/$storyId/edit'
    | '/admin/access-management'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/modules'
    | '/admin/orders'
    | '/admin/stores'
    | '/admin/zones'
    | '/items/$itemId'
    | '/stories/$storyId'
    | '/vendor/orders'
    | '/admin/access-management/$userId/edit'
    | '/admin/categories/$categoryId/edit'
    | '/admin/modules/$moduleId/edit'
    | '/admin/stores/$storeId/edit'
    | '/admin/zones/$zoneId/edit'
    | '/admin/zones/$zoneId/modules'
    | '/admin/orders/$orderId'
    | '/admin/stores/$storeId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/settings'
    | '/_authenticated/vendor'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/cashback/$cashbackId'
    | '/_authenticated/cashback/$orderId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/items/new'
    | '/_authenticated/loans/$loanId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/stories/new'
    | '/_authenticated/users/$userId'
    | '/_authenticated/apps/'
    | '/_authenticated/cashback/'
    | '/_authenticated/chats/'
    | '/_authenticated/classifieds/'
    | '/_authenticated/emprestimos/'
    | '/_authenticated/fees/'
    | '/_authenticated/help-center/'
    | '/_authenticated/items/'
    | '/_authenticated/loans/'
    | '/_authenticated/payable-accounts/'
    | '/_authenticated/settings/'
    | '/_authenticated/stories/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/admin/categories/new'
    | '/_authenticated/admin/customers/$userId'
    | '/_authenticated/admin/modules/new'
    | '/_authenticated/admin/stores/new'
    | '/_authenticated/admin/zones/new'
    | '/_authenticated/items/$itemId/edit'
    | '/_authenticated/stories/$storyId/edit'
    | '/_authenticated/admin/access-management/'
    | '/_authenticated/admin/categories/'
    | '/_authenticated/admin/customers/'
    | '/_authenticated/admin/modules/'
    | '/_authenticated/admin/orders/'
    | '/_authenticated/admin/stores/'
    | '/_authenticated/admin/zones/'
    | '/_authenticated/items/$itemId/'
    | '/_authenticated/stories/$storyId/'
    | '/_authenticated/vendor/orders/'
    | '/_authenticated/admin/access-management/$userId/edit'
    | '/_authenticated/admin/categories/$categoryId/edit'
    | '/_authenticated/admin/modules/$moduleId/edit'
    | '/_authenticated/admin/stores/$storeId/edit'
    | '/_authenticated/admin/zones/$zoneId/edit'
    | '/_authenticated/admin/zones/$zoneId/modules'
    | '/_authenticated/admin/orders/$orderId/'
    | '/_authenticated/admin/stores/$storeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stories/': {
      id: '/_authenticated/stories/'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof AuthenticatedStoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/payable-accounts/': {
      id: '/_authenticated/payable-accounts/'
      path: '/payable-accounts'
      fullPath: '/payable-accounts'
      preLoaderRoute: typeof AuthenticatedPayableAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans/': {
      id: '/_authenticated/loans/'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items/': {
      id: '/_authenticated/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/': {
      id: '/_authenticated/fees/'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emprestimos/': {
      id: '/_authenticated/emprestimos/'
      path: '/emprestimos'
      fullPath: '/emprestimos'
      preLoaderRoute: typeof AuthenticatedEmprestimosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classifieds/': {
      id: '/_authenticated/classifieds/'
      path: '/classifieds'
      fullPath: '/classifieds'
      preLoaderRoute: typeof AuthenticatedClassifiedsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashback/': {
      id: '/_authenticated/cashback/'
      path: '/cashback'
      fullPath: '/cashback'
      preLoaderRoute: typeof AuthenticatedCashbackIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stories/new': {
      id: '/_authenticated/stories/new'
      path: '/stories/new'
      fullPath: '/stories/new'
      preLoaderRoute: typeof AuthenticatedStoriesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/loans/$loanId': {
      id: '/_authenticated/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AuthenticatedLoansLoanIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items/new': {
      id: '/_authenticated/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof AuthenticatedItemsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashback/$orderId': {
      id: '/_authenticated/cashback/$orderId'
      path: '/cashback/$orderId'
      fullPath: '/cashback/$orderId'
      preLoaderRoute: typeof AuthenticatedCashbackOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashback/$cashbackId': {
      id: '/_authenticated/cashback/$cashbackId'
      path: '/cashback/$cashbackId'
      fullPath: '/cashback/$cashbackId'
      preLoaderRoute: typeof AuthenticatedCashbackCashbackIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/orders/': {
      id: '/_authenticated/vendor/orders/'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof AuthenticatedVendorOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/stories/$storyId/': {
      id: '/_authenticated/stories/$storyId/'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof AuthenticatedStoriesStoryIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items/$itemId/': {
      id: '/_authenticated/items/$itemId/'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AuthenticatedItemsItemIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/zones/': {
      id: '/_authenticated/admin/zones/'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AuthenticatedAdminZonesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stores/': {
      id: '/_authenticated/admin/stores/'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AuthenticatedAdminStoresIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders/': {
      id: '/_authenticated/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modules/': {
      id: '/_authenticated/admin/modules/'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AuthenticatedAdminModulesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers/': {
      id: '/_authenticated/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories/': {
      id: '/_authenticated/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/access-management/': {
      id: '/_authenticated/admin/access-management/'
      path: '/access-management'
      fullPath: '/admin/access-management'
      preLoaderRoute: typeof AuthenticatedAdminAccessManagementIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/stories/$storyId/edit': {
      id: '/_authenticated/stories/$storyId/edit'
      path: '/stories/$storyId/edit'
      fullPath: '/stories/$storyId/edit'
      preLoaderRoute: typeof AuthenticatedStoriesStoryIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items/$itemId/edit': {
      id: '/_authenticated/items/$itemId/edit'
      path: '/items/$itemId/edit'
      fullPath: '/items/$itemId/edit'
      preLoaderRoute: typeof AuthenticatedItemsItemIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/zones/new': {
      id: '/_authenticated/admin/zones/new'
      path: '/zones/new'
      fullPath: '/admin/zones/new'
      preLoaderRoute: typeof AuthenticatedAdminZonesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stores/new': {
      id: '/_authenticated/admin/stores/new'
      path: '/stores/new'
      fullPath: '/admin/stores/new'
      preLoaderRoute: typeof AuthenticatedAdminStoresNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modules/new': {
      id: '/_authenticated/admin/modules/new'
      path: '/modules/new'
      fullPath: '/admin/modules/new'
      preLoaderRoute: typeof AuthenticatedAdminModulesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers/$userId': {
      id: '/_authenticated/admin/customers/$userId'
      path: '/customers/$userId'
      fullPath: '/admin/customers/$userId'
      preLoaderRoute: typeof AuthenticatedAdminCustomersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories/new': {
      id: '/_authenticated/admin/categories/new'
      path: '/categories/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stores/$storeId/': {
      id: '/_authenticated/admin/stores/$storeId/'
      path: '/stores/$storeId'
      fullPath: '/admin/stores/$storeId'
      preLoaderRoute: typeof AuthenticatedAdminStoresStoreIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders/$orderId/': {
      id: '/_authenticated/admin/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedAdminOrdersOrderIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/zones/$zoneId/modules': {
      id: '/_authenticated/admin/zones/$zoneId/modules'
      path: '/zones/$zoneId/modules'
      fullPath: '/admin/zones/$zoneId/modules'
      preLoaderRoute: typeof AuthenticatedAdminZonesZoneIdModulesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/zones/$zoneId/edit': {
      id: '/_authenticated/admin/zones/$zoneId/edit'
      path: '/zones/$zoneId/edit'
      fullPath: '/admin/zones/$zoneId/edit'
      preLoaderRoute: typeof AuthenticatedAdminZonesZoneIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stores/$storeId/edit': {
      id: '/_authenticated/admin/stores/$storeId/edit'
      path: '/stores/$storeId/edit'
      fullPath: '/admin/stores/$storeId/edit'
      preLoaderRoute: typeof AuthenticatedAdminStoresStoreIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modules/$moduleId/edit': {
      id: '/_authenticated/admin/modules/$moduleId/edit'
      path: '/modules/$moduleId/edit'
      fullPath: '/admin/modules/$moduleId/edit'
      preLoaderRoute: typeof AuthenticatedAdminModulesModuleIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories/$categoryId/edit': {
      id: '/_authenticated/admin/categories/$categoryId/edit'
      path: '/categories/$categoryId/edit'
      fullPath: '/admin/categories/$categoryId/edit'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesCategoryIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/access-management/$userId/edit': {
      id: '/_authenticated/admin/access-management/$userId/edit'
      path: '/access-management/$userId/edit'
      fullPath: '/admin/access-management/$userId/edit'
      preLoaderRoute: typeof AuthenticatedAdminAccessManagementUserIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCategoriesNewRoute: typeof AuthenticatedAdminCategoriesNewRoute
  AuthenticatedAdminCustomersUserIdRoute: typeof AuthenticatedAdminCustomersUserIdRoute
  AuthenticatedAdminModulesNewRoute: typeof AuthenticatedAdminModulesNewRoute
  AuthenticatedAdminStoresNewRoute: typeof AuthenticatedAdminStoresNewRoute
  AuthenticatedAdminZonesNewRoute: typeof AuthenticatedAdminZonesNewRoute
  AuthenticatedAdminAccessManagementIndexRoute: typeof AuthenticatedAdminAccessManagementIndexRoute
  AuthenticatedAdminCategoriesIndexRoute: typeof AuthenticatedAdminCategoriesIndexRoute
  AuthenticatedAdminCustomersIndexRoute: typeof AuthenticatedAdminCustomersIndexRoute
  AuthenticatedAdminModulesIndexRoute: typeof AuthenticatedAdminModulesIndexRoute
  AuthenticatedAdminOrdersIndexRoute: typeof AuthenticatedAdminOrdersIndexRoute
  AuthenticatedAdminStoresIndexRoute: typeof AuthenticatedAdminStoresIndexRoute
  AuthenticatedAdminZonesIndexRoute: typeof AuthenticatedAdminZonesIndexRoute
  AuthenticatedAdminAccessManagementUserIdEditRoute: typeof AuthenticatedAdminAccessManagementUserIdEditRoute
  AuthenticatedAdminCategoriesCategoryIdEditRoute: typeof AuthenticatedAdminCategoriesCategoryIdEditRoute
  AuthenticatedAdminModulesModuleIdEditRoute: typeof AuthenticatedAdminModulesModuleIdEditRoute
  AuthenticatedAdminStoresStoreIdEditRoute: typeof AuthenticatedAdminStoresStoreIdEditRoute
  AuthenticatedAdminZonesZoneIdEditRoute: typeof AuthenticatedAdminZonesZoneIdEditRoute
  AuthenticatedAdminZonesZoneIdModulesRoute: typeof AuthenticatedAdminZonesZoneIdModulesRoute
  AuthenticatedAdminOrdersOrderIdIndexRoute: typeof AuthenticatedAdminOrdersOrderIdIndexRoute
  AuthenticatedAdminStoresStoreIdIndexRoute: typeof AuthenticatedAdminStoresStoreIdIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCategoriesNewRoute: AuthenticatedAdminCategoriesNewRoute,
    AuthenticatedAdminCustomersUserIdRoute:
      AuthenticatedAdminCustomersUserIdRoute,
    AuthenticatedAdminModulesNewRoute: AuthenticatedAdminModulesNewRoute,
    AuthenticatedAdminStoresNewRoute: AuthenticatedAdminStoresNewRoute,
    AuthenticatedAdminZonesNewRoute: AuthenticatedAdminZonesNewRoute,
    AuthenticatedAdminAccessManagementIndexRoute:
      AuthenticatedAdminAccessManagementIndexRoute,
    AuthenticatedAdminCategoriesIndexRoute:
      AuthenticatedAdminCategoriesIndexRoute,
    AuthenticatedAdminCustomersIndexRoute:
      AuthenticatedAdminCustomersIndexRoute,
    AuthenticatedAdminModulesIndexRoute: AuthenticatedAdminModulesIndexRoute,
    AuthenticatedAdminOrdersIndexRoute: AuthenticatedAdminOrdersIndexRoute,
    AuthenticatedAdminStoresIndexRoute: AuthenticatedAdminStoresIndexRoute,
    AuthenticatedAdminZonesIndexRoute: AuthenticatedAdminZonesIndexRoute,
    AuthenticatedAdminAccessManagementUserIdEditRoute:
      AuthenticatedAdminAccessManagementUserIdEditRoute,
    AuthenticatedAdminCategoriesCategoryIdEditRoute:
      AuthenticatedAdminCategoriesCategoryIdEditRoute,
    AuthenticatedAdminModulesModuleIdEditRoute:
      AuthenticatedAdminModulesModuleIdEditRoute,
    AuthenticatedAdminStoresStoreIdEditRoute:
      AuthenticatedAdminStoresStoreIdEditRoute,
    AuthenticatedAdminZonesZoneIdEditRoute:
      AuthenticatedAdminZonesZoneIdEditRoute,
    AuthenticatedAdminZonesZoneIdModulesRoute:
      AuthenticatedAdminZonesZoneIdModulesRoute,
    AuthenticatedAdminOrdersOrderIdIndexRoute:
      AuthenticatedAdminOrdersOrderIdIndexRoute,
    AuthenticatedAdminStoresStoreIdIndexRoute:
      AuthenticatedAdminStoresStoreIdIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedVendorRouteRouteChildren {
  AuthenticatedVendorOrdersIndexRoute: typeof AuthenticatedVendorOrdersIndexRoute
}

const AuthenticatedVendorRouteRouteChildren: AuthenticatedVendorRouteRouteChildren =
  {
    AuthenticatedVendorOrdersIndexRoute: AuthenticatedVendorOrdersIndexRoute,
  }

const AuthenticatedVendorRouteRouteWithChildren =
  AuthenticatedVendorRouteRoute._addFileChildren(
    AuthenticatedVendorRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedVendorRouteRoute: typeof AuthenticatedVendorRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCashbackCashbackIdRoute: typeof AuthenticatedCashbackCashbackIdRoute
  AuthenticatedCashbackOrderIdRoute: typeof AuthenticatedCashbackOrderIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedItemsNewRoute: typeof AuthenticatedItemsNewRoute
  AuthenticatedLoansLoanIdRoute: typeof AuthenticatedLoansLoanIdRoute
  AuthenticatedStoriesNewRoute: typeof AuthenticatedStoriesNewRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedCashbackIndexRoute: typeof AuthenticatedCashbackIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedClassifiedsIndexRoute: typeof AuthenticatedClassifiedsIndexRoute
  AuthenticatedEmprestimosIndexRoute: typeof AuthenticatedEmprestimosIndexRoute
  AuthenticatedFeesIndexRoute: typeof AuthenticatedFeesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedItemsIndexRoute: typeof AuthenticatedItemsIndexRoute
  AuthenticatedLoansIndexRoute: typeof AuthenticatedLoansIndexRoute
  AuthenticatedPayableAccountsIndexRoute: typeof AuthenticatedPayableAccountsIndexRoute
  AuthenticatedStoriesIndexRoute: typeof AuthenticatedStoriesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedItemsItemIdEditRoute: typeof AuthenticatedItemsItemIdEditRoute
  AuthenticatedStoriesStoryIdEditRoute: typeof AuthenticatedStoriesStoryIdEditRoute
  AuthenticatedItemsItemIdIndexRoute: typeof AuthenticatedItemsItemIdIndexRoute
  AuthenticatedStoriesStoryIdIndexRoute: typeof AuthenticatedStoriesStoryIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedVendorRouteRoute: AuthenticatedVendorRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCashbackCashbackIdRoute: AuthenticatedCashbackCashbackIdRoute,
  AuthenticatedCashbackOrderIdRoute: AuthenticatedCashbackOrderIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedItemsNewRoute: AuthenticatedItemsNewRoute,
  AuthenticatedLoansLoanIdRoute: AuthenticatedLoansLoanIdRoute,
  AuthenticatedStoriesNewRoute: AuthenticatedStoriesNewRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedCashbackIndexRoute: AuthenticatedCashbackIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedClassifiedsIndexRoute: AuthenticatedClassifiedsIndexRoute,
  AuthenticatedEmprestimosIndexRoute: AuthenticatedEmprestimosIndexRoute,
  AuthenticatedFeesIndexRoute: AuthenticatedFeesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedItemsIndexRoute: AuthenticatedItemsIndexRoute,
  AuthenticatedLoansIndexRoute: AuthenticatedLoansIndexRoute,
  AuthenticatedPayableAccountsIndexRoute:
    AuthenticatedPayableAccountsIndexRoute,
  AuthenticatedStoriesIndexRoute: AuthenticatedStoriesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedItemsItemIdEditRoute: AuthenticatedItemsItemIdEditRoute,
  AuthenticatedStoriesStoryIdEditRoute: AuthenticatedStoriesStoryIdEditRoute,
  AuthenticatedItemsItemIdIndexRoute: AuthenticatedItemsItemIdIndexRoute,
  AuthenticatedStoriesStoryIdIndexRoute: AuthenticatedStoriesStoryIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
